// Pulls the icons the game uses out of game-icons.net (CC BY 3.0, via @iconify-json/game-icons)
// into src/scenes/iconPaths.ts, so the game draws them as vectors with no files to load.
// The names come from every `icon: "…"` in src/roguelike and the UI_ICON table in
// src/scenes/icons.ts. Run: node scripts/icons/build-icons.mjs
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("../../", import.meta.url).pathname;
const set = JSON.parse(readFileSync(join(root, "node_modules/@iconify-json/game-icons/icons.json"), "utf8"));

const names = new Set();
for (const f of readdirSync(join(root, "src/roguelike"))) {
  const src = readFileSync(join(root, "src/roguelike", f), "utf8");
  for (const m of src.matchAll(/icon: "([a-z0-9-]+)"/g)) names.add(m[1]);
}
const ui = readFileSync(join(root, "src/scenes/icons.ts"), "utf8").match(/UI_ICON = \{([\s\S]*?)\} as const/)[1];
for (const m of ui.matchAll(/: "([a-z0-9-]+)"/g)) names.add(m[1]);

const out = {};
for (const name of [...names].sort()) {
  const icon = set.icons[name] ?? set.icons[set.aliases?.[name]?.parent];
  if (!icon) throw new Error(`game-icons has no "${name}"`);
  out[name] = [...icon.body.matchAll(/ d="([^"]+)"/g)].map((m) => m[1]);
}
writeFileSync(
  join(root, "src/scenes/iconPaths.ts"),
  `// Generated by scripts/icons/build-icons.mjs — do not edit.\n// Icons by game-icons.net (Lorc, Delapouite and contributors), CC BY 3.0.\n` +
    `export const ICON_PATHS: Record<string, string[]> = ${JSON.stringify(out, null, 0)};\n`,
);
console.log(`${Object.keys(out).length} icons`);
